# Use the generic fortify/github-action to submit FoD scans.
# If granular controls are required, use the following to setup the use shell commands to call scancentral and fodupload
# - fortify/github-action/setup@v1
# 
# Details of the tools definitions can be found in:
# - https://github.com/fortify/github-action/blob/main/setup/src/constants.ts
# - https://github.com/fortify/tool-definitions/tree/main/v1
# 
# If tools are needed to be hosted in airgap environment, provide the tools definition file via `TOOL_DEFINITIONS` variable when using `fortify/github-action`.
# A sample of the tools definition file can be found in:
# - https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip

name: "Fortify SCSAST (Remote Translate)"

on: 
  workflow_dispatch:
env:
  SSC_APP_NAME: webgoat.net
  SSC_APP_VER_NAME: "scsast_remotetranslate"

jobs:
  sast:
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-2022
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Fortify SAST Assessment
        uses: fortify/github-action@v2
        with:
          sast-scan: true
        env:
          SSC_URL: ${{secrets.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SC_SAST_TOKEN: ${{secrets.CLIENT_AUTH_TOKEN}}
          SSC_APPVERSION: "${{env.SSC_APP_NAME}}:${{env.SSC_APP_VER_NAME}}"
        #   PACKAGE_EXTRA_OPTS: -exclude ".gitlab" 
          SC_SAST_SENSOR_VERSION: 24.4